# Generated by Django 3.2.8 on 2021-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blurb',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_games',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Played Games'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_genres',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Preferred Game Genres'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=3, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='time_zone',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
