# Generated by Django 3.2.9 on 2021-11-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211102_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='play_style',
            field=models.CharField(blank=True, choices=[('Hardcore', 'Hardcore'), ('Casual', 'Casual')], max_length=50, null=True),
        ),
    ]
