# Generated by Django 3.2.9 on 2021-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211103_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishgame',
            name='api_id',
        ),
        migrations.AddField(
            model_name='wishgame',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wishgame',
            name='pic_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wishgame',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wishgame',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='OwnedGame',
        ),
    ]
