# Generated by Django 3.2.9 on 2021-11-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_wishgame_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishgame',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='wishgame',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wishgame',
            name='pic_link',
        ),
        migrations.RemoveField(
            model_name='wishgame',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='wishgame',
            name='release_date',
        ),
        migrations.AddField(
            model_name='wishgame',
            name='api_id',
            field=models.IntegerField(default=44),
            preserve_default=False,
        ),
    ]
