# Generated by Django 3.2.9 on 2021-11-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211104_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishgame',
            name='api_id',
            field=models.IntegerField(unique=True),
        ),
    ]
